In [1]:
import numpy as np

# NumPy Ndarray

Creating a ndarray object

In [2]:
a = np.array
print(a)
print(type(a))

<built-in function array>
<class 'builtin_function_or_method'>


In [3]:
b = np.array([1, 2, 3])
print(b)
print(type(b))
print(b.ndim)
print(b.itemsize, "bytes")
print(b.dtype)
print(b.size)
print(b.shape)

[1 2 3]
<class 'numpy.ndarray'>
1
8 bytes
int64
3
(3,)


In [4]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.ndim)
print(c.itemsize, "bytes")
print(c.dtype)
print(c.size)
print(c.shape)

[[1 2 3]
 [4 5 6]]
2
8 bytes
int64
6
(2, 3)


In [5]:
d = np.array([1, 3, 5, 7], dtype=complex)
print(d)
print(d.ndim)
print(d.itemsize, "bytes")
print(d.dtype)
print(d.size)
print(d.shape)

[1.+0.j 3.+0.j 5.+0.j 7.+0.j]
1
16 bytes
complex128
4
(4,)


In [6]:
e = np.array([1, 3, 5, 7], dtype=float)
print(e)
print(e.ndim)
print(e.itemsize, "bytes")
print(e.dtype)
print(e.size)
print(e.shape)

[1. 3. 5. 7.]
1
8 bytes
float64
4
(4,)


In [7]:
f = np.array([1, 3, 5, 7], dtype=str)
print(f)
print(f.ndim)
print(f.itemsize, "bytes")
print(f.dtype)
print(f.size)
print(f.shape)

['1' '3' '5' '7']
1
4 bytes
<U1
4
(4,)


In [8]:
g = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])
print(g)
print(g.ndim)
print(g.itemsize, "bytes")
print(g.dtype)
print(g.size)
print(g.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]
2
8 bytes
int64
12
(3, 4)


By the shape of the array, we mean the number of rows and columns of a multi-dimensional array. However, the numpy module provides us the way to reshape the array by changing the number of rows and columns of the multi-dimensional array.

The reshape() function associated with the ndarray object is used to reshape the array. It accepts the two parameters indicating the row and columns of the new shape of the array.

In [9]:
h = np.array([[1,2],[3,4],[5,6]])
print(h)
print(h.ndim)
print(h.itemsize, "bytes")
print(h.dtype)
print(h.size)
print(h.shape)

[[1 2]
 [3 4]
 [5 6]]
2
8 bytes
int64
6
(3, 2)


In [10]:
print(h.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [11]:
print(h.reshape(1, 6))
print(h.reshape(6))

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


Slicing in the NumPy array is the way to extract a range of elements from an array. Slicing in the array is performed in the same way as it is performed in the python list.

In [12]:
print(h[1])
print(h[0:])

[3 4]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(h[1:])

[[3 4]
 [5 6]]


In [14]:
print(h[1:2])

[[3 4]]


In [15]:
print(h[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [16]:
print(h[0][::-1])

[2 1]


In [17]:
print(h[::-1][::-1])

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(h[0, 1])
print(h[0][1])
print(h[2, 0])
print(h[2][0])

2
2
5
5


The linspace() function returns the evenly spaced values over the given interval. The following example returns the 10 evenly separated values over the given interval 5-15

In [19]:
print(np.linspace(5, 10))

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]


In [20]:
print(np.linspace(5, 15))

[ 5.          5.20408163  5.40816327  5.6122449   5.81632653  6.02040816
  6.2244898   6.42857143  6.63265306  6.83673469  7.04081633  7.24489796
  7.44897959  7.65306122  7.85714286  8.06122449  8.26530612  8.46938776
  8.67346939  8.87755102  9.08163265  9.28571429  9.48979592  9.69387755
  9.89795918 10.10204082 10.30612245 10.51020408 10.71428571 10.91836735
 11.12244898 11.32653061 11.53061224 11.73469388 11.93877551 12.14285714
 12.34693878 12.55102041 12.75510204 12.95918367 13.16326531 13.36734694
 13.57142857 13.7755102  13.97959184 14.18367347 14.3877551  14.59183673
 14.79591837 15.        ]


In [21]:
print(np.linspace(5, 20))

[ 5.          5.30612245  5.6122449   5.91836735  6.2244898   6.53061224
  6.83673469  7.14285714  7.44897959  7.75510204  8.06122449  8.36734694
  8.67346939  8.97959184  9.28571429  9.59183673  9.89795918 10.20408163
 10.51020408 10.81632653 11.12244898 11.42857143 11.73469388 12.04081633
 12.34693878 12.65306122 12.95918367 13.26530612 13.57142857 13.87755102
 14.18367347 14.48979592 14.79591837 15.10204082 15.40816327 15.71428571
 16.02040816 16.32653061 16.63265306 16.93877551 17.24489796 17.55102041
 17.85714286 18.16326531 18.46938776 18.7755102  19.08163265 19.3877551
 19.69387755 20.        ]


In [22]:
print(np.linspace(5, 30))

[ 5.          5.51020408  6.02040816  6.53061224  7.04081633  7.55102041
  8.06122449  8.57142857  9.08163265  9.59183673 10.10204082 10.6122449
 11.12244898 11.63265306 12.14285714 12.65306122 13.16326531 13.67346939
 14.18367347 14.69387755 15.20408163 15.71428571 16.2244898  16.73469388
 17.24489796 17.75510204 18.26530612 18.7755102  19.28571429 19.79591837
 20.30612245 20.81632653 21.32653061 21.83673469 22.34693878 22.85714286
 23.36734694 23.87755102 24.3877551  24.89795918 25.40816327 25.91836735
 26.42857143 26.93877551 27.44897959 27.95918367 28.46938776 28.97959184
 29.48979592 30.        ]


In [23]:
print(np.linspace(5, 40))

[ 5.          5.71428571  6.42857143  7.14285714  7.85714286  8.57142857
  9.28571429 10.         10.71428571 11.42857143 12.14285714 12.85714286
 13.57142857 14.28571429 15.         15.71428571 16.42857143 17.14285714
 17.85714286 18.57142857 19.28571429 20.         20.71428571 21.42857143
 22.14285714 22.85714286 23.57142857 24.28571429 25.         25.71428571
 26.42857143 27.14285714 27.85714286 28.57142857 29.28571429 30.
 30.71428571 31.42857143 32.14285714 32.85714286 33.57142857 34.28571429
 35.         35.71428571 36.42857143 37.14285714 37.85714286 38.57142857
 39.28571429 40.        ]


In [24]:
print(np.linspace(5, 15, 10))

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [25]:
print(np.linspace(1, 10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [26]:
print(np.linspace(2, 10, 10))

[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


The NumPy provides the max(), min(), and sum() functions which are used to find the maximum, minimum, and sum of the array elements respectively.

In [27]:
i = np.array([1,2,3,10,15,4])  
print(i)
print(i.min())
print(i.max())
print(i.sum())

[ 1  2  3 10 15  4]
1
15
35


A NumPy multi-dimensional array is represented by the axis where axis-0 represents the columns and axis-1 represents the rows. We can mention the axis to perform row-level or column-level calculations like the addition of row or column elements.

In [28]:
j = np.array([[1,2,30],[10,15,4]]) 
print(j)
print(j.min(axis=0))
print(j.min(axis=1))

[[ 1  2 30]
 [10 15  4]]
[1 2 4]
[1 4]


In [29]:
print(j.max(axis=0))
print(j.max(axis=1))

[10 15 30]
[30 15]


In [30]:
print(j.sum(axis=0))
print(j.sum(axis=1))

[11 17 34]
[33 29]


The sqrt() and std() functions associated with the numpy array are used to find the square root and standard deviation of the array elements respectively.

Standard deviation means how much each element of the array varies from the mean value of the numpy array.

In [31]:
k = np.array([[1,2,30],[10,15,4]]) 
print(k)
print(np.sqrt(k))
print(np.std(k))

[[ 1  2 30]
 [10 15  4]]
[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


The numpy module allows us to perform the arithmetic operations on multi-dimensional arrays directly.

In [32]:
l = np.array([[1,2,30],[10,15,4]])
m = np.array([[1,2,3],[12, 19, 29]])
print(l)
print(m)

[[ 1  2 30]
 [10 15  4]]
[[ 1  2  3]
 [12 19 29]]


In [33]:
print(l+m)

[[ 2  4 33]
 [22 34 33]]


In [34]:
print(l-m)

[[  0   0  27]
 [ -2  -4 -25]]


In [35]:
print(l*m)

[[  1   4  90]
 [120 285 116]]


In [36]:
print(l/m)

[[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [37]:
print(l//m)

[[ 1  1 10]
 [ 0  0  0]]


In [38]:
print(l%m)

[[ 0  0  0]
 [10 15  4]]


The numpy provides us with the vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional arrays vertically or horizontally.

In [39]:
n = np.array([[1,2,30],[10,15,4]])
o = np.array([[1,2,3],[12, 19, 29]])
print(n)
print(o)

[[ 1  2 30]
 [10 15  4]]
[[ 1  2  3]
 [12 19 29]]


In [40]:
print(np.vstack((n,o)))
print(np.vstack((n,o)).ndim)

[[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
2


In [41]:
print(np.hstack((n, o)))
print(np.hstack((n, o)).ndim)

[[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]
2
